/**
 * Stable GitHub URLs for Boing Network protocol + SDK docs (normative upstream).
 * @see https://github.com/Boing-Network/boing.network/blob/main/docs/HANDOFF-DEPENDENT-PROJECTS.md
 */

const BASE = 'https://github.com/Boing-Network/boing.network/blob/main/docs';

export const BOING_NETWORK_HANDOFF_DEPENDENT_PROJECTS_URL = `${BASE}/HANDOFF-DEPENDENT-PROJECTS.md`;
export const BOING_NETWORK_THREE_CODEBASE_ALIGNMENT_URL = `${BASE}/THREE-CODEBASE-ALIGNMENT.md`;
export const BOING_NETWORK_RPC_API_SPEC_URL = `${BASE}/RPC-API-SPEC.md`;
export const BOING_NETWORK_E2_PARTNER_APP_NATIVE_BOING_URL = `${BASE}/E2-PARTNER-APP-NATIVE-BOING.md`;
export const BOING_NETWORK_BOING_CANONICAL_DEPLOY_ARTIFACTS_URL = `${BASE}/BOING-CANONICAL-DEPLOY-ARTIFACTS.md`;
export const BOING_NETWORK_BOING_L1_DEX_ENGINEERING_URL = `${BASE}/BOING-L1-DEX-ENGINEERING.md`;
export const BOING_NETWORK_NATIVE_AMM_LP_VAULT_URL = `${BASE}/NATIVE-AMM-LP-VAULT.md`;
export const BOING_NETWORK_NATIVE_LP_SHARE_TOKEN_URL = `${BASE}/NATIVE-LP-SHARE-TOKEN.md`;
export const BOING_NETWORK_BOING_PATTERN_AMM_LIQUIDITY_URL = `${BASE}/BOING-PATTERN-AMM-LIQUIDITY.md`;
export const BOING_NETWORK_NATIVE_DEX_LEDGER_ROUTER_URL = `${BASE}/NATIVE-DEX-LEDGER-ROUTER.md`;
